version: "3.9"
services:
  build-manual:
    build: .
    command: 
      - /bin/ash
      - -c
      - |
        pdflatex smlm-lab-manual
        bibtex smlm-lab-manual
        pdflatex smlm-lab-manual
        pdflatex smlm-lab-manual
    volumes:
      - .:/opt
